### PR TITLE
improve default values

### LINKED ISSUE #35: Replace the defaults with something more generic
If you generate a package and say yes to all the defaults, you get a package called wagtail-localize authored by Karl Hobley, etc. Lets replace the defaults with something more 'defaultey'.
https://github.com/wagtail/cookiecutter-wagtail-package/blob/main/cookiecutter.json

### PR DESCRIPTION
**Pull request by chris48s**
Closes #35

I think these represent a better set of default values. Open to other suggestions though.

### CODE REVIEW

**Review by zerolab — APPROVED** [review]
Ah, good ole' Llama savers

non-blocking: is the `llamasavers-llama-save` needed for linting purposes, still?

**Comment by chris48s** [comment]
> is the `llamasavers-llama-save` needed for linting purposes, still?

I'm not sure I understand the question. There may be some bit of context I'm missing here.

I updated the Circle CI build to reference `wagtail-llama-savers-llama-save` instead of `wagtail-localize`. That is not long for this world. We'll move to GitHub actions soon, but we're still going to want to spit out a package accepting all the defaults and test/lint the output. Is that what you mean?

If I've missed the point, let me know..

**Comment by zerolab** [comment]
@chris48s WK nightly was failing CI because of black so `llama-savers` became `llama-savers-llama-save`, hence my question. This is one of those random noise nitpicks (where `llama-savers` is shorter and sweeter) which stem more from curiosity than anything else. Do not let this block anything

**Comment by chris48s** [comment]
:llama: This now has the requisite number of llamas per line to make the linters happy :laughing:

**Pull request merged**
